# Generated by Django 4.2 on 2023-05-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_company_category_id_jobseeker_address_jobseeker_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprovider',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
    ]
