# Generated by Django 4.2 on 2023-05-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_country'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Job Provider', 'Job Provider'), ('Job Seeker', 'Job Seeker')], default='admin', max_length=50),
        ),
    ]
