# Generated by Django 4.2 on 2023-05-22 06:41

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
