# Generated by Django 4.2 on 2023-05-23 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_jobseeker_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprovider',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
    ]
