# Generated by Django 4.2 on 2023-05-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_jobprovider_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='profile_img',
            field=models.ImageField(default='profiles/profile.png', upload_to='profiles/'),
        ),
    ]
