# Generated by Django 4.2 on 2023-05-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_jobseeker_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='country',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='mobile_number',
        ),
    ]
