# Generated by Django 4.2 on 2023-05-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_company_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': True, 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
