# Generated by Django 4.2 on 2023-05-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_company_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
    ]
