# Generated by Django 4.2 on 2023-06-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_company_category_id_alter_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, default='profiles/profile.png', null=True, upload_to='company_images/'),
        ),
    ]
