# Generated by Django 4.2 on 2023-06-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(default='profiles/profile.png', upload_to='customprofile/'),
        ),
    ]
