# Generated by Django 4.2 on 2023-05-22 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
        ('users', '0008_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skills', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('country', models.CharField(max_length=255)),
                ('education', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.categories')),
                ('job_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobprovider')),
            ],
        ),
    ]
