# Generated by Django 4.2 on 2023-06-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0008_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='status',
            field=models.IntegerField(blank=True, choices=[(None, 'Pending'), (1, 'Accepted'), (0, 'Rejected')], null=True),
        ),
    ]
