# Generated by Django 4.2 on 2023-06-03 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0009_jobapply_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
    ]
