# Generated by Django 4.2 on 2023-06-08 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
