# Generated by Django 4.2 on 2023-05-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0002_alter_job_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
