# Generated by Django 4.2 on 2023-05-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0005_jobapply_apply_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'managed': True, 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelTable(
            name='job',
            table='Jobs',
        ),
        migrations.AlterModelTable(
            name='jobapply',
            table='Applications',
        ),
    ]
