# Generated by Django 4.2 on 2023-06-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0007_alter_job_options_alter_jobapply_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.IntegerField(blank=True, choices=[(None, 'Pending'), (1, 'Accepted'), (0, 'Rejected')], null=True),
        ),
    ]
